services:
  - type: web
    name: your-fastapi-app
    env: python
    buildCommand: ""
    startCommand: uvicorn main:app --host 0.0.0.0 --port 8000
    envVars:
      - key: ENV
        value: production
